### ISSUE TITLE
Microsoft.NET.Test.Sdk v.16.3.0 does not respect LogFileName and appends underscore with date to file name

### ISSUE THREAD

**Issue by hunyhabib** [microsoft/vstest#2256]
## Description
when running dotnet vstest with Microsoft.NET.Test.Sdk 16.3.0 an _ with currentdate appended to file name causing failure after that due to name missmatch. 
>

## Steps to reproduce
run 
dotnet vstest x.dll --logger:'trx;LogFileName=xyz'

## Expected behavior
test result gets published with samefile name xyz.trx

## Actual behavior
test result got published under different name 
Results File: xyz_2019-11-25_14-25-23-354.trx

## Diagnostic logs
{"correlationId":"168744fb-17a2-45b4-a293-e8b8f33398fd","brand":"shared","environment":"Development","application":"shared-products","message":"Executed endpoint 'Shared.Products.Controllers.ProductsController.GetProductsBySSN (Shared.Products)'","@timestamp":"2019-11-25T14:25:21.9664617Z","level":"INFO","logger":"Microsoft.AspNetCore.Routing.EndpointMiddleware","machine":"shared-products-integrationtests-c99mr"}
{"correlationId":"168744fb-17a2-45b4-a293-e8b8f33398fd","brand":"shared","environment":"Development","application":"shared-products","message":"Executed endpoint 'Shared.Products.Controllers.ProductsController.GetProductsBySSN (Shared.Products)'","@timestamp":"2019-11-25T14:25:21.9665025Z","level":"INFO","logger":"Microsoft.AspNetCore.Routing.EndpointMiddleware","machine":"shared-products-integrationtests-c99mr"}
{"brand":"shared","environment":"Development","application":"shared-products","message":"Request finished in 24.1281ms 200 application/json; charset=utf-8","@timestamp":"2019-11-25T14:25:21.9665455Z","level":"INFO","logger":"Microsoft.AspNetCore.Hosting.Internal.WebHost","machine":"shared-products-integrationtests-c99mr"}
{"brand":"shared","environment":"Development","application":"shared-products","message":"Request finished in 24.1281ms 200 application/json; charset=utf-8","@timestamp":"2019-11-25T14:25:21.9665665Z","level":"INFO","logger":"Microsoft.AspNetCore.Hosting.Internal.WebHost","machine":"shared-products-integrationtests-c99mr"}
Results File: xyz_2019-11-25_14-25-23-354.trx

Total tests: 14. Passed: 14. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 50.1112 Seconds

**Comment by jayaranigarg** [comment]
@hunyhabib : When you run via commandline, it uses dotnet sdk to run your test dll. Please install latest dotnet sdk and see if that works for you. This issue has already been fixed by us.

**Comment by hunyhabib** [comment]
@jayaranigarg i am using mcr.microsoft.com/dotnet/core/sdk:2.2 docker image. the thing is when i downgraded Microsoft.NET.Test.Sdk to V 16.2 it works as expected

**Comment by hunyhabib** [comment]
which version you mean 2.2.207 ?

**Comment by jayaranigarg** [comment]
Yes please

**Comment by hunyhabib** [comment]
![image](https://user-images.githubusercontent.com/34410233/69631437-2f94dd00-104e-11ea-8d2e-f2fd0c778cdf.png)
Still Exists also with updated sdk
![image](https://user-images.githubusercontent.com/34410233/69631575-57844080-104e-11ea-98f2-715939fa7022.png)

**Comment by jayaranigarg** [comment]
![image](https://user-images.githubusercontent.com/17309452/69707964-c03bed80-1120-11ea-984d-a113f46fb6c3.png)

Tried on our end, and it seems to work fine. Can you see what version of Test Execution commandline it is showing for you? I am using 3.1.0-preview2.19525.6 version for dotnet sdk. Can you please try with 3.1 version of sdk?

**Comment by ShreyasRmsft** [comment]
@hunyhabib any updates here?

**Comment by hunyhabib** [comment]
yah it works with the latest version .. but what was changed suddenly with sdk 2.2 because it worked for 2 month and now got corrupted suddenly..
